title: "BOSTON INDIES 🔮💀"

markdown: kramdown
future: false
timezone: America/New_York

permalink: /news/:year/:month/:day/:title

url: https://witchcat.net

legal: "© Boston Indies, all rights reserved."



discord_invite: "https://discord.gg/sJrv3z7kgj"



collections:
  events:
    output: true
    permalink: /:collection/:title



# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
