title: "BOSTON INDIES 🔮💀"
about: "Boston Indies is a rad community of local indie developers in Massachusetts! We host demo nights, talks, and more! Come hang out!"
featured_video: "uBfi7h6qEMQ"

markdown: kramdown
future: true
timezone: America/New_York

url: https://www.bostonindies.com

legal: "© Boston Indies, all rights reserved."

meetup: "https://www.meetup.com/bostongamedev/"

collections:
  events:
    output: true
    permalink: :collection/:title
  locations:
    output: false
  socials:
    output: false
  links:
    output: false
  badges:
    output: false
  information:
    output: false

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed