title: "BOSTON INDIES 🔮💀"

about: "Boston Indies is a community of dedicated independent game developers in Massachusetts and the surrounding area. We define ourselves in connection with our community spirit and our group objectives. We gather in person once a month to talk about the art and craft of making games, and to share our work with each other."

markdown: kramdown
future: true
timezone: America/New_York

url: https://witchcat.net

legal: "© Boston Indies, all rights reserved."

discord_invite: "https://discord.gg/sJrv3z7kgj"



collections:
  events:
    output: true
    permalink: :collection/:title
  locations:
    output: false
  socials:
    output: false
  links:
    output: false

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed